workflows:
  ios-build:
    name: iOS Build (no codesign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.10.1  # Убедись, что версия cocoapods актуальна
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build IPA (no codesign)
        script: |
          flutter build ios --release --no-codesign --workspace ios/Runner.xcworkspace --scheme Runner --xcconfig ios/Flutter/Release.xcconfig

    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Runner.ipa
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip

    publishing:
      email:
        recipients:
          - evan.00270@gmail.com
